### ISSUE TITLE
FATEL ERROR with  php version 8.0.30 and below

### ISSUE THREAD

**Issue by Bhimashankar3002** [Metagauss-com/buddybot#77]
[20-Dec-2024 06:38:48 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getOption() on null in C:\wamp64\www\buddybot\wp-content\plugins\buddybot\admin\responses\moroot.php:27
Stack trace:
#0 C:\wamp64\www\buddybot\wp-content\plugins\buddybot\moroot.php(25): BuddyBot\Admin\Responses\MoRoot->setApiKey()
#1 C:\wamp64\www\buddybot\wp-content\plugins\buddybot\admin\responses\chatbot.php(202): BuddyBot\MoRoot->setAll()
#2 C:\wamp64\www\buddybot\wp-content\plugins\buddybot\buddybot.php(44): BuddyBot\Admin\Responses\ChatBot->__construct()
#3 C:\wamp64\www\buddybot\wp-admin\includes\plugin.php(2387): include_once('C:\\wamp64\\www\\b...')
#4 C:\wamp64\www\buddybot\wp-admin\includes\plugin.php(673): plugin_sandbox_scrape('buddybot/buddyb...')
#5 C:\wamp64\www\buddybot\wp-admin\plugins.php(60): activate_plugin('buddybot/buddyb...', 'http://localhos...', false)
#6 {main}
  thrown in C:\wamp64\www\buddybot\wp-content\plugins\buddybot\admin\responses\moroot.php on line 27
  
  
  
  
  
  
  
  
![image](https://github.com/user-attachments/assets/9a77d83b-9dcb-4a5b-912a-33a48b60f60d)

**Comment by Bhimashankar3002** [comment]
![image](https://github.com/user-attachments/assets/3dc84d06-a285-4865-b9f9-1381a1e3a42d)

**Comment by Bhimashankar3002** [comment]
CHECK
